name: CI/CD Pipeline

on:
  # Trigger workflow on push to the main branch or pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up environment (e.g., Node.js, Python, etc.)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Run tests
    - name: Run Tests
      run: npm test

  deploy:
    name: Deploy to Production
    needs: build  # Only runs if the 'build' job is successful
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Deploy application (example using AWS CLI)
    - name: Deploy to S3 Bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws s3 sync ./build s3://your-bucket-name --delete
